encryption = "gpg"
[gpg]
  recipient = "7F30678CF4053CEDDCB852EB7AC0F35EF1924EEA"

[edit]
  command = "code"
  args = ["--wait"]

[data]
  personal = false
  wsl      = false
  machine  = "desktop" # available types "sb3", "sl3", "x1", "desktop"

